// GENERATED by scripts/make-cursor.mjs — do not edit by hand.
// Edit resources/cursor-arrow.svg and re-run `node scripts/make-cursor.mjs`.

/** The pointer outline. Filled; the renderer supplies every colour. */
export const CURSOR_ARROW = 'M3.6 3.6 21.4 14.1 13.0 15.9 10.3 24.1Z'

/** Side of the square the arrow was drawn in. */
export const CURSOR_BOX = 30

/**
 * Where the arrow's point is, and therefore the cursor's hotspot — the pixel a
 * click actually lands on.
 */
export const CURSOR_TIP = { x: 3.6, y: 3.6 }
