// Wraps an authored shader body into a complete WGSL module for the island.
//
// The authoring contract keeps uniform access as BARE NAMES (`angle`,
// `colorA`) so the WGSL and the TS twin read the same. WGSL has no
// module-scope view of uniform values, so the wrapper injects a `let`
// preamble INSIDE `fn material`'s opening brace — binding each manifest key
// to its slot — rather than asking authors to write accessor calls. The body
// must therefore declare the exact signature for its class; anything else is
// a named validation error before the GPU ever sees the code.
//
// Pixel addressing matches the CPU twins exactly: the fragment stage floors
// @builtin(position) (which is pixel-center, +0.5) back to integer pixel
// coordinates, so island pixel (x, y) and twin(x, y) evaluate the same
// point. That is what lets the harness hold the two producers to a tight
// diff instead of an edge-fuzz excuse.
//
// Uniform block layout (shared with packUniforms below and the TS twins):
//   info:  vec4f            = (width, height, pxScale, seed)
//   slots: array<vec4f, 12> = one vec4 per manifest uniform, declaration order
//     float/bool/enum -> .x        vec2 -> .xy        color -> full vec4

import type { MaterialUniformValue, RGBA, Vec2 } from '../types'
import { MAX_UNIFORMS, type ShaderClass, type ShaderManifest } from './registry'

/** Signatures, per class. The wrapper refuses a body that lacks its own. */
export const MATERIAL_SIGNATURES: Record<ShaderClass, string> = {
  procedural: 'fn material(p: vec2f, size: vec2f) -> vec4f {',
  base: 'fn material(p: vec2f, size: vec2f, src: vec4f) -> vec4f {',
  sdf: 'fn material(p: vec2f, size: vec2f, dist: f32) -> vec4f {',
  backdrop: 'fn material(p: vec2f, size: vec2f, behind: vec4f) -> vec4f {',
}

export class WgslWrapError extends Error {}

function slotBinding(key: string, type: string, slot: number): string {
  switch (type) {
    case 'color':
      return `  let ${key}: vec4f = u.slots[${slot}];`
    case 'vec2':
      return `  let ${key}: vec2f = u.slots[${slot}].xy;`
    default:
      // float, bool (0/1) and enum (option index) all travel as one f32.
      return `  let ${key}: f32 = u.slots[${slot}].x;`
  }
}

/**
 * The complete module: uniforms, class bindings, the author's code with the
 * preamble injected, and the fullscreen entry points.
 */
export function wrapMaterialWgsl(manifest: ShaderManifest, body: string): string {
  const signature = MATERIAL_SIGNATURES[manifest.class]
  const at = body.indexOf(signature)
  if (at < 0) {
    throw new WgslWrapError(
      `shader "${manifest.id}" (${manifest.class}) must declare exactly: ${signature.slice(0, -2)}`,
    )
  }
  if (body.indexOf(signature, at + 1) >= 0) {
    throw new WgslWrapError(`shader "${manifest.id}" declares fn material more than once`)
  }

  const preamble = manifest.uniforms.map((u, i) => slotBinding(u.key, u.type, i)).join('\n')
  const cut = at + signature.length
  const authored = body.slice(0, cut) + '\n' + preamble + body.slice(cut)

  const classBindings =
    manifest.class === 'base'
      ? '@group(0) @binding(1) var src_tex: texture_2d<f32>;\n'
      : manifest.class === 'sdf'
        ? '@group(0) @binding(1) var sdf_tex: texture_2d<f32>;\n'
        : ''

  const fsInner =
    manifest.class === 'base'
      ? `  let src = textureLoad(src_tex, vec2i(p), 0);\n  return material(p, u.info.xy, src);`
      : manifest.class === 'sdf'
        ? `  let dist = textureLoad(sdf_tex, vec2i(p), 0).r;\n  return material(p, u.info.xy, dist);`
        : `  return material(p, u.info.xy);`

  return `// generated by wrap-wgsl.ts for "${manifest.id}" — do not edit
struct MaterialUniforms {
  info: vec4f,
  slots: array<vec4f, ${MAX_UNIFORMS}>,
}
@group(0) @binding(0) var<uniform> u: MaterialUniforms;
${classBindings}
${authored}

@vertex
fn vs_main(@builtin(vertex_index) vi: u32) -> @builtin(position) vec4f {
  // One triangle covering the viewport; no vertex buffer, no varyings.
  let x = f32(i32(vi & 1u) * 4 - 1);
  let y = f32(i32(vi >> 1u) * 4 - 1);
  return vec4f(x, y, 0.0, 1.0);
}

@fragment
fn fs_main(@builtin(position) pos: vec4f) -> @location(0) vec4f {
  // floor(pixel-center) == the integer pixel the CPU twin evaluates.
  let p = floor(pos.xy);
  ${fsInner.trimStart()}
}
`
}

/** info + one vec4 per declared uniform, in declaration order. */
export function packUniforms(
  manifest: ShaderManifest,
  resolved: Record<string, MaterialUniformValue>,
  width: number,
  height: number,
  pxScale: number,
  seed = 0,
): Float32Array {
  const out = new Float32Array(4 * (1 + MAX_UNIFORMS))
  out[0] = width
  out[1] = height
  out[2] = pxScale
  out[3] = seed
  manifest.uniforms.forEach((spec, i) => {
    const base = 4 + i * 4
    const v = resolved[spec.key]
    if (spec.type === 'color') {
      const c = v as RGBA
      out[base] = c.r
      out[base + 1] = c.g
      out[base + 2] = c.b
      out[base + 3] = c.a
    } else if (spec.type === 'vec2') {
      const p = v as Vec2
      out[base] = p.x
      out[base + 1] = p.y
    } else if (spec.type === 'bool') {
      out[base] = v === true ? 1 : 0
    } else {
      out[base] = typeof v === 'number' ? v : 0
    }
  })
  return out
}
