// Turns the authored pointer SVG into the path data the renderer draws.
//
//   resources/cursor-arrow.svg                        the shape, editable
//   src/renderer/src/engine/render/cursor-paths.ts    the same shape as data
//
// Same arrangement as the logo (scripts/make-logo.mjs): the SVG is the source
// and the TS is generated, so the file you can open in a design tool and the
// file the app compiles cannot drift apart. The renderer does not read SVG at
// runtime — a cursor is rebuilt from a string on every badge change, and
// parsing a document to do it would be work for nothing.
//
// The reading is in scripts/cursor-svg.mjs, which also accepts an SVG exported
// straight out of Polyform — a big viewBox, transforms on every node, guide
// layers and a frame background. That is the whole reason this is a file and
// not a string in the source.
//
// Usage: node scripts/make-cursor.mjs [path/to/some.svg]
import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { CURSOR_BOX, readCursorSvg } from './cursor-svg.mjs'

const REPO = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')
const SRC = path.join(REPO, 'resources', 'cursor-arrow.svg')
const OUT = path.join(REPO, 'src', 'renderer', 'src', 'engine', 'render', 'cursor-paths.ts')

// An argument lets you point at an export without overwriting the source first
// — read it, see what it would produce, then decide.
const src = process.argv[2] ? path.resolve(process.argv[2]) : SRC

let read
try {
  read = readCursorSvg(fs.readFileSync(src, 'utf8'))
} catch (err) {
  console.error(`${path.relative(REPO, src)}: ${err instanceof Error ? err.message : err}`)
  process.exit(1)
}
const { paths, tip, notes } = read

const out = `// GENERATED by scripts/make-cursor.mjs — do not edit by hand.
// Edit resources/cursor-arrow.svg and re-run \`node scripts/make-cursor.mjs\`.

/** The pointer outline. Filled; the renderer supplies every colour. */
export const CURSOR_ARROW = '${paths.join(' ')}'

/**
 * Side of the square the arrow is drawn in. Fixed: the badge disc, the rounding
 * and the rim are all measured in this space, so a source drawn at another size
 * is rescaled into it rather than carried through.
 */
export const CURSOR_BOX = ${CURSOR_BOX}

/**
 * Where the arrow's point is, and therefore the cursor's hotspot — the pixel a
 * click actually lands on.
 */
export const CURSOR_TIP = { x: ${tip.x}, y: ${tip.y} }
`
fs.writeFileSync(OUT, out)
for (const note of notes) console.log(`ignored ${note}`)
console.log(`cursor-paths.ts written: ${paths.length} path(s), box ${CURSOR_BOX}, tip ${tip.x},${tip.y}`)
