// Turns the authored pointer SVG into the path data the renderer draws.
//
//   resources/cursor-arrow.svg                        the shape, editable
//   src/renderer/src/engine/render/cursor-paths.ts    the same shape as data
//
// Same arrangement as the logo (scripts/make-logo.mjs): the SVG is the source
// and the TS is generated, so the file you can open in a design tool and the
// file the app compiles cannot drift apart. The renderer does not read SVG at
// runtime — a cursor is rebuilt from a string on every badge change, and
// parsing a document to do it would be work for nothing.
//
// Usage: node scripts/make-cursor.mjs
import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'

const REPO = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')
const SRC = path.join(REPO, 'resources', 'cursor-arrow.svg')
const OUT = path.join(REPO, 'src', 'renderer', 'src', 'engine', 'render', 'cursor-paths.ts')

const svg = fs.readFileSync(SRC, 'utf8')

const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]
if (!viewBox) {
  console.error('cursor-arrow.svg has no viewBox — the renderer needs one to place the badge')
  process.exit(1)
}
const size = viewBox.trim().split(/\s+/).map(Number)
if (size.length !== 4 || size.some((n) => !Number.isFinite(n))) {
  console.error(`cursor-arrow.svg has an unreadable viewBox: "${viewBox}"`)
  process.exit(1)
}

// Every path in the file, concatenated. More than one is legal — an arrow with
// a separate detail is a reasonable thing to draw — and they fill as subpaths.
const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1].replace(/\s+/g, ' ').trim())
if (paths.length === 0) {
  console.error('cursor-arrow.svg has no <path d="…"> to read')
  process.exit(1)
}

// The tip is the hotspot, so it is checked rather than assumed: a shape whose
// first point has moved would aim somewhere other than where it points, and
// nothing downstream could tell.
const first = paths[0].match(/^M\s*(-?[\d.]+)[ ,]+(-?[\d.]+)/)
if (!first) {
  console.error(`the first path does not start with an absolute moveto: "${paths[0].slice(0, 40)}"`)
  process.exit(1)
}
const tip = { x: Number(first[1]), y: Number(first[2]) }

const out = `// GENERATED by scripts/make-cursor.mjs — do not edit by hand.
// Edit resources/cursor-arrow.svg and re-run \`node scripts/make-cursor.mjs\`.

/** The pointer outline. Filled; the renderer supplies every colour. */
export const CURSOR_ARROW = '${paths.join(' ')}'

/** Side of the square the arrow was drawn in. */
export const CURSOR_BOX = ${size[2]}

/**
 * Where the arrow's point is, and therefore the cursor's hotspot — the pixel a
 * click actually lands on.
 */
export const CURSOR_TIP = { x: ${tip.x}, y: ${tip.y} }
`
fs.writeFileSync(OUT, out)
console.log(`cursor-paths.ts written: ${paths.length} path(s), box ${size[2]}, tip ${tip.x},${tip.y}`)
