// GENERATED by scripts/make-logo.mjs — do not edit by hand.
// Re-run `node scripts/make-logo.mjs` after changing the logo geometry.

/** Square viewBox centred on the glyph. */
export const MARK_VIEWBOX = '310 256 1524 1524'

/** Outer silhouette + counter, filled with fill-rule="evenodd". */
export const MARK_GLYPH =
  'M 554 310 L 1016 314 L 1400 402 L 1578 682 L 1590 956 L 1400 1220 L 1180 1284 L 910 1300 L 910 1576 L 842 1722 L 570 1726 Z M 874 644 L 1198 652 L 1226 800 L 1198 962 L 874 972 Z'

/** Coarse facets: enough to read as low-poly at 14px, no more. */
export const MARK_FACETS =
  'M 1016 314 L 874 644 M 874 644 L 554 310 M 874 644 L 559 782 M 559 782 L 554 310 M 1400 402 L 1198 652 M 1198 652 L 1016 314 M 1578 682 L 1198 652 M 1590 956 L 1226 800 M 1226 800 L 1578 682 M 1400 1220 L 1198 962 M 1198 962 L 1590 956 M 1180 1284 L 1198 962 M 910 1300 L 874 972 M 874 972 L 1180 1284 M 910 1576 L 565 1254 M 565 1254 L 910 1300 M 874 972 L 565 1254 M 570 1726 L 910 1576 M 570 1726 L 565 1254 M 874 972 L 559 782 M 565 1254 L 559 782'

/** The skin gradient, shared with resources/polyform-*.svg. */
export const MARK_STOPS: { at: number; color: string }[] = [{"at":0,"color":"#15EAD6"},{"at":0.34,"color":"#35C8E4"},{"at":0.68,"color":"#6C74E8"},{"at":1,"color":"#A322E0"}]

export const MARK_INK = '#23262A'
