// GENERATED by scripts/make-logo.mjs — do not edit by hand.
// Re-run `node scripts/make-logo.mjs` after changing the logo geometry.

/** Square viewBox centred on the letter. */
export const MARK_VIEWBOX = '407.69 315 1416.09 1416.09'

/** The whole letter as ONE path: four clockwise subpaths, nonzero fill.
 *  One path means one coverage computation, so no hairline where the
 *  stem, the bars and the bowl meet. */
export const MARK_GLYPH =
  'M 624 315.41 L 824.59 315.41 A 80 80 0 0 1 904.59 395.41 L 904.59 1651.09 A 80 80 0 0 1 824.59 1731.09 L 624 1731.09 A 80 80 0 0 1 544 1651.09 L 544 395.41 A 80 80 0 0 1 624 315.41 Z M 1007.32 315 L 1193.89 315 L 1193.89 315 L 1193.89 656.95 L 1193.89 656.95 L 1007.32 656.95 A 80 80 0 0 1 927.32 576.95 L 927.32 395 A 80 80 0 0 1 1007.32 315 Z M 1002.32 956.05 L 1193.32 956.05 L 1193.32 956.05 L 1193.32 1297.94 L 1193.32 1297.94 L 1002.32 1297.94 A 80 80 0 0 1 922.32 1217.94 L 922.32 1036.05 A 80 80 0 0 1 1002.32 956.05 Z M 1190.9 315.11 A 496.58 491.41 0 0 1 1190.9 1297.92 L 1190.9 954.92 A 149.97 148.4 0 0 0 1190.9 658.11 Z'

/** Gradient axis in the same user space as MARK_GLYPH. */
export const MARK_AXIS = {"x1":864.17,"y1":315,"x2":1230.09,"y2":1731.09}

/** The skin gradient, shared with resources/polyform-*.svg. */
export const MARK_STOPS: { at: number; color: string }[] = [{"at":0,"color":"#15EAD6"},{"at":0.34,"color":"#35C8E4"},{"at":0.68,"color":"#6C74E8"},{"at":1,"color":"#A322E0"}]
